name: Azure Static Web Apps

on:
  push:
    branches: [main]
    paths:
      - "Web/**"
      - ".github/workflows/azure-static-web-apps.yml"
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]
    paths:
      - "Web/**"
      - ".github/workflows/azure-static-web-apps.yml"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build_and_deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: Azure/static-web-apps-deploy@v1
        env:
          ADMOB_PUBLISHER_ID: ${{ secrets.ADMOB_PUBLISHER_ID }}
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: Web
          api_location: Web/api
          output_location: dist

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close preview environment
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
